stages:
  - test

test-job:
  image: ghcr.io/cirruslabs/flutter:3.10.6
  stage: test
  script:
    - sudo apt-get update
    - sudo apt-get --yes install protobuf-compiler
    - git submodule update --init --recursive
    - bash test/ci-test.sh
