name: cryptographic_id
description:
  This is an Android App to create and verify identities based on ed25519
  signatures. It can be used to verify devices (e.g. replace tpm-otp) or
  people who are in posession of a private key.

repository: https://gitlab.com/cryptographic_id/cryptographic-id-flutter/
issue_tracker: https://gitlab.com/cryptographic_id/cryptographic-id-flutter/-/issues
publish_to: 'none'
version: 0.4.0+10

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  barcode_widget: ^2.0.3
  cryptography: ^2.4.0
  fixnum: ^1.1.0
  flutter_secure_storage: ^8.0.0
  intl: ^0.17.0
  pointycastle: ^3.6.2
  protobuf: ^2.1.0
  qr_code_scanner: ^1.0.1
  sqflite: ^2.2.5
  sqflite_common: ^2.4.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - sql/
    - sql/upgrade/

platforms:
  linux:
