name: cryptographic_id
description:
  This is an Android App to create and verify identities based on ed25519
  signatures. It can be used to verify devices (e.g. replace tpm-otp) or
  people who are in posession of a private key.

publish_to: 'none'
version: 0.1.4+2

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  barcode_widget: ^2.0.3
  cryptography: ^2.0.5
  fixnum: ^1.0.1
  flutter_secure_storage: ^6.1.0
  intl: ^0.17.0
  protobuf: ^2.1.0
  qr_code_scanner: ^1.0.0
  sqflite: ^2.0.3
  sqflite_common: ^2.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - sql/

platforms:
  linux:
