on: [push, pull_request]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - run: git submodule update --init --recursive
      - run: sudo apt-get update
      - run: sudo apt-get --yes install protobuf-compiler
      - run: bash test/ci-test.sh
